project_id = "xlumyobcdjmhwymverhr"

[functions.send-inquiry-email]
verify_jwt = false

[functions.create-enrollment-checkout]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-session]
verify_jwt = true
